### ISSUE TITLE
Page params

### ISSUE THREAD

**Issue by benkraus** [maizzle/starter-postmark#12]
Having an issue with this starter I can't seem to replicate with the Netlify style starter.

Just by checking out fresh and starting a new starter project, some of the output templates when running `build` or `build production` result in the password reset emails containing `{{ page.company.product }}` (which exists in the config file), but only in the body.

The header and footer also contains this in the template, but it's replaced by the build system just fine. It seems if it's in the body, the build system is somehow skipping over it.

Thoughts?

**Comment by cossssmin** [comment]
In the body, `{{ page.company.name }}` is inside a `<raw>` tag, which disables parsing expressions. While this is on purpose for things like `{{total}}` (imagine it's an expression that Postmark will evaluate), it shouldn't be applied to stuff like the company name, which we define in `config.js` and which _Maizzle_ should evaluate.

This is an intentional my mistake from when I ported the starter over from Nunjucks to PostHTML - back then, escaping with `@{{ }}` didn't work great, so I just wrapped the entire thing in a `<raw>` tag so the build would work.

I'll have a look at it when I get some time, but basically you need to remove that wrapping `<raw>` tag and add a `@` in front of any `{{ }}` expression that you don't want Maizzle to evaluate (i.e. `@{{name}}`, `@{{total}}`).

**Comment by benkraus** [comment]
Oh, perfect, not sure how I missed the `<raw>` tag. I'll look into that, thanks for the prompt response!
